version: "3.8"

services:
  backend:
    build: ./backend
    container_name: revconnect-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.aws
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
